fix code: 修复上传multipartdata时,Content-Type请求头格式不对的问题
daixinkai/feign.net pull request #13
Opened 2022-08-22 06:22 UTC by wumiao55

2022-08-22 13:43 UTC, daixinkai reviewed
FeignOptionsExtensions.ConfigureJsonSettings 可以配置选项

2022-08-22 13:44 UTC, daixinkai approved these changes

2022-08-22 13:46 UTC, daixinkai approved these changes

2022-08-22 13:53 UTC, daixinkai reviewed
代码并无不妥,请问是报错了吗?

2022-08-22 14:00 UTC, daixinkai requested changes
MultipartFormDataContent 这种写法并无不妥,请问是报错了吗?

2022-08-23 02:04 UTC, wumiao55 commented
> FeignOptionsExtensions.ConfigureJsonSettings 可以配置选项 Newtownsoft再.net core 3.1后默认弃用了



> MultipartFormDataContent 这种写法并无不妥,请问是报错了吗?
   在使用feign.net进行企业微信api接口开发,调用[上传临时素材](https://developer.work.weixin.qq.com/document/path/90871)时,
接口返回"empty media data,",如下图:

![图二](https://user-images.githubusercontent.com/104432990/186052059-17cd1498-3f5f-4da8-b2cc-c921f7b9fac6.jpg)

  通过分析,我发现是请求头中"Content-Type"中boundary的值带了双引号,导致请求无法被微信服务接口识别到素材数据,
于是将boundary的值去掉双引号后,再次请求接口返回成功了,如下图:

![图三](https://user-images.githubusercontent.com/104432990/186052580-b2b5222c-3f40-48f5-9001-d938df40fed2.jpg)

2022-08-23 14:10 UTC, daixinkai commented
> 
[https://developers.de/blogs/damir_dobric/archive/2013/09/10/problems-with-webapi-multipart-content-upload-and-boundary-quot-quotes.aspx](url)
查找资料确实存在此问题,但是引号也是标准,所以我增加了一个配置用来指定是否去除引号,代码我已提交,故关闭此pull了.
如果你要在.net core app 3.0+启用 NewtonsoftJsonProvider 的话,可以自定义一个Provider,然后在Options中替换它

2022-08-23 14:10 UTC, closed without merging

2022-08-24 02:36 UTC, wumiao55 commented
thanks, 测试ok, 麻烦发布一版最新的nuget包

2022-08-24 05:21 UTC, daixinkai commented
> thanks, 测试ok, 麻烦发布一版最新的nuget包

已更新1.3.3,并且做了些细微调整